In [19]:
! python -m pip install "pymongo[srv]"
import pandas as pd

Requirement already satisfied: pymongo[srv] in /usr/local/python/3.12.1/lib/python3.12/site-packages (4.17.0)
WARNING: pymongo 4.17.0 does not provide the extra 'srv'
Requirement already satisfied: dnspython<3.0.0,>=2.6.1 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from pymongo[srv]) (2.8.0)

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: pip install --upgrade pip

In [16]:
from pymongo import MongoClient
from pymongo.server_api import ServerApi
uri = "mongodb+srv://repositorios28_db_user:FD7PTkgoKK2jwFOZ@cluster0.pyosdvz.mongodb.net/?appName=Cluster0"
# Create a new client and connect to the server
client = MongoClient(uri, server_api=ServerApi('1'))
# Send a ping to confirm a successful connection
try:
    client.admin.command('ping')
    print("Pinged your deployment. You successfully connected to MongoDB!")
except Exception as e:
    print(e)

Pinged your deployment. You successfully connected to MongoDB!

In [17]:
db_mflix = client['sample_mflix']

In [18]:
collection_users = db_mflix['users']
users = collection_users.find({})
df_users = pd.DataFrame(users)
df_users

,_id,name,email,password,preferences
0,59b99db4cfa9a34dcd7885b6,Ned Stark,sean_bean@gameofthron.es,$2b$12$UREFwsRUoyF0CRqGNK0LzO0HM/jLhgUCNNIJ9RJ...,NaN
1,59b99db4cfa9a34dcd7885b7,Robert Baratheon,mark_addy@gameofthron.es,$2b$12$yGqxLG9LZpXA2xVDhuPnSOZd.VURVkz7wgOLY3p...,NaN
2,59b99db5cfa9a34dcd7885b8,Jaime Lannister,nikolaj_coster-waldau@gameofthron.es,$2b$12$6vz7wiwO.EI5Rilvq1zUc./9480gb1uPtXcahDx...,NaN
3,59b99db5cfa9a34dcd7885b9,Catelyn Stark,michelle_fairley@gameofthron.es,$2b$12$fiaTH5Sh1zKNFX2i/FTEreWGjxoJxvmV7XL.qlf...,NaN
4,59b99db6cfa9a34dcd7885ba,Cersei Lannister,lena_headey@gameofthron.es,$2b$12$FExjgr7CLhNCa.oUsB9seub8mqcHzkJCFZ8heMc...,NaN
...,...,...,...,...,...
180,59b99e08cfa9a34dcd78866a,Shawn Mccormick,shawn_mccormick@fakegmail.com,$2b$12$fVJEFj7SXlqT0EmE9k00FuZLNH52NFSPriUqm8G...,NaN
181,59b99e09cfa9a34dcd78866b,Anthony Hurst,anthony_hurst@fakegmail.com,$2b$12$9M2cew6pOM.35LY474rMkeVD4WxfvF2lDtVg60j...,NaN
182,59b99e09cfa9a34dcd78866c,Ashlee Hart,ashlee_hart@fakegmail.com,$2b$12$S707opDk6HG/Lqk7MaHeQ.1N36I6kEUOhRv/RQE...,NaN
183,5db1c37e4a68c31f10cf0a98,Magical Mr. Mistoffelees,magicz@cats.com,somehashedpw,NaN
184,5db1c37e4a68c31f10cf0a9f,foo,foobaz@bar.com,foobar,{}

In [30]:
collection_movies=db_mflix['movies']
movies = collection_movies.find({})
df_movies= pd.DataFrame(movies)
df_movies

,_id,plot,genres,runtime,cast,poster,title,fullplot,languages,released,...,awards,lastupdated,year,imdb,countries,type,tomatoes,num_mflix_comments,writers,metacritic
0,573a1390f29313caabcd42e8,A group of bandits stage a brazen train hold-u...,"[Short, Western]",11.0,"[A.C. Abadie, Gilbert M. 'Broncho Billy' Ander...",https://m.media-amazon.com/images/M/MV5BMTU3Nj...,The Great Train Robbery,Among the earliest existing films in American ...,[English],1903-12-01,...,"{'wins': 1, 'nominations': 0, 'text': '1 win.'}",2015-08-13 00:27:59.177000000,1903,"{'rating': 7.4, 'votes': 9847, 'id': 439}",[USA],movie,"{'viewer': {'rating': 3.7, 'numReviews': 2559,...",0,NaN,NaN
1,573a1390f29313caabcd446f,"A greedy tycoon decides, on a whim, to corner ...","[Short, Drama]",14.0,"[Frank Powell, Grace Henderson, James Kirkwood...",NaN,A Corner in Wheat,"A greedy tycoon decides, on a whim, to corner ...",[English],1909-12-13,...,"{'wins': 1, 'nominations': 0, 'text': '1 win.'}",2015-08-13 00:46:30.660000000,1909,"{'rating': 6.6, 'votes': 1375, 'id': 832}",[USA],movie,"{'viewer': {'rating': 3.6, 'numReviews': 109, ...",1,NaN,NaN
2,573a1390f29313caabcd4803,"Cartoon figures announce, via comic strip ball...","[Animation, Short, Comedy]",7.0,[Winsor McCay],https://m.media-amazon.com/images/M/MV5BYzg2Nj...,"Winsor McCay, the Famous Cartoonist of the N.Y...",Cartoonist Winsor McCay agrees to create a lar...,[English],1911-04-08,...,"{'wins': 1, 'nominations': 0, 'text': '1 win.'}",2015-08-29 01:09:03.030000000,1911,"{'rating': 7.3, 'votes': 1034, 'id': 1737}",[USA],movie,"{'viewer': {'rating': 3.4, 'numReviews': 89, '...",0,"[Winsor McCay (comic strip ""Little Nemo in Slu...",NaN
3,573a1390f29313caabcd4eaf,"A woman, with the aid of her police officer sw...","[Crime, Drama]",88.0,"[Jane Gail, Ethel Grandin, William H. Turner, ...",https://m.media-amazon.com/images/M/MV5BYzk0YW...,Traffic in Souls,NaN,[English],1913-11-24,...,"{'wins': 1, 'nominations': 0, 'text': '1 win.'}",2015-09-15 02:07:14.247000000,1913,"{'rating': 6.0, 'votes': 371, 'id': 3471}",[USA],movie,"{'viewer': {'rating': 3.0, 'numReviews': 85, '...",1,NaN,NaN
4,573a1390f29313caabcd50e5,"The cartoonist, Winsor McCay, brings the Dinos...","[Animation, Short, Comedy]",12.0,"[Winsor McCay, George McManus, Roy L. McCardell]",https://m.media-amazon.com/images/M/MV5BMTQxNz...,Gertie the Dinosaur,Winsor Z. McCay bets another cartoonist that h...,[English],1914-09-15,...,"{'wins': 1, 'nominations': 0, 'text': '1 win.'}",2015-08-18 01:03:15.313000000,1914,"{'rating': 7.3, 'votes': 1837, 'id': 4008}",[USA],movie,"{'viewer': {'rating': 3.7, 'numReviews': 29}, ...",0,[Winsor McCay],NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21344,573a13faf29313caabded1d6,A-Gu enlists a group of contract killers in th...,[Comedy],110.0,"[Hsiao-chuan Chang, Qian Wan, Tang Sui, Yann Y...",NaN,The Laundryman,A-Gu enlists a group of contract killers in th...,[Mandarin],2015-07-11,...,"{'wins': 0, 'nominations': 2, 'text': '2 nomin...",2015-09-15 06:14:05.163000000,2015,"{'rating': 6.3, 'votes': 27, 'id': 4801514}",[Taiwan],movie,NaN,1,NaN,NaN
21345,573a13faf29313caabded406,"Karol, an ordinary young man, runs into a much...",[Thriller],90.0,"[Filip Plawiak, Adam Woronowicz, Julia Kijowsk...",NaN,The Red Spider,"Karol, an ordinary young man, runs into a much...","[Polish, English]",2015-11-20,...,"{'wins': 0, 'nominations': 1, 'text': '1 nomin...",2015-08-18 00:52:59.093000000,2015,"{'rating': 7.4, 'votes': 16, 'id': 4817256}","[Poland, Czech Republic, Slovakia]",movie,NaN,0,"[Marcin Koszalka, Lukasz M. Maciejewski, Marta...",NaN
21346,573a13fbf29313caabdedf30,Guy's tragic death is a shock for the Leblanc ...,[Drama],102.0,"[Maxim Gaudette, Karelle Tremblay, Valerie Cad...",NaN,Our Loved Ones,Guy's tragic death is a shock for the Leblanc ...,[French],2015-08-12,...,"{'wins': 0, 'nominations': 1, 'text': '1 nomin...",2015-08-27 00:18:43.727000000,2015,"{'rating': 7.4, 'votes': 5, 'id': 4881276}",[Canada],movie,NaN,0,[Anne èmond],NaN
21347,573a13fbf29313caabdedf31,NaN,[Documentary],115.0,[Chantal Akerman],NaN,No Home Movie,NaN,[French],2015-08-10,...,"{'wins': 0, 'nominations': 1, 'text': '1 nomin...",2015-08-13 18:35:53.927000000,2015,"{'rating': 3.8, 'votes': 5, 'id': 4881016}","[Belgium, France]",movie,NaN,0,[Chantal Akerman],NaN
21348,573a13fbf29313caabdee03b,"Sex and love. Some seek it, some need it, some...","[Comedy, Drama, Romance]",91.0,"[Holly Aird, Eileen Atkins, Hugh Bonneville, T...",https://m.media-amazon.com/images/M/MV5BMTA5OT...,Scenes of a Sexual Nature,Various Londeners meet people in Hampstead Hea...,[English],NaT,...,"{'wins': 0, 'nominations': 1, 'text': '1 nomin...",2015-09-12 09:51:28.903000000,2006,"{'rating': 6.1, 'votes': 4125, 'id': 475380}",[UK],movie,"{'website': 'http://www.tinpanfilms.com/', 'vi...",0,[Aschlin Ditta],NaN