In [ ]:
! pip install mysql-connector-python==9.1.0
! pip install pandas==2.2.3
! pip install sqlalchemy==2.0.36

Requirement already satisfied: mysql-connector-python==9.1.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (9.1.0)

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: pip install --upgrade pip
Requirement already satisfied: pandas==2.2.3 in /usr/local/python/3.12.1/lib/python3.12/site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from pandas==2.2.3) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.12/site-packages (from pandas==2.2.3) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from pandas==2.2.3) (2026.2)
Requirement already satisfied: tzdata>=2022.7 in /home/codespace/.local/lib/python3.12/site-packages (from pandas==2.2.3) (2025.3)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas==2.2.3) (1.17.0)

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: pip install --upgrade pip
Requirement already satisfied: sqlalchemy==2.0.36 in /usr/local/python/3.12.1/lib/python3.12/site-packages (2.0.36)
Requirement already satisfied: typing-extensions>=4.6.0 in /home/codespace/.local/lib/python3.12/site-packages (from sqlalchemy==2.0.36) (4.15.0)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from sqlalchemy==2.0.36) (3.5.1)

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: pip install --upgrade pip

In [8]:
import sqlalchemy as db
import pandas as pd

In [35]:
engine = db.create_engine("mysql+mysqlconnector://root:root@localhost:3310/retail_db")
conn = engine.connect()

In [38]:
df_departments = pd.read_sql_table('departments', con=conn)
df_departments

   department_id department_name
0              2         Fitness
1              3        Footwear
2              4         Apparel
3              5            Golf
4              6        Outdoors
5              7        Fan Shop

In [41]:
df_departments=pd.read_sql_query("select * from departments where department_id=3",con=conn)
df_departments

   department_id department_name
0              3        Footwear